group:
  repos: |
    MSevey/workflows
    MSevey/workflows-2
  files:
    - source: .github/dependabot.njk
      dest: .github/dependabot.yml
      template:
        deps: [{ ecosystem: "docker" }, { ecosystem: "github-actions" }]
