# This workflow is an example of a combination of automatic and manual release.
# The triggers are:
#   - Push
#   - Schedule
#   - Workflow Dispatch
#
# This workflow uses the `if` conditions to control when the CI runs versus when
# a release is also created.
#
# The CI runs when pull requests are created and also when code is merged into
# main, i.e. push events to main.
#
# It will run nightly at 1:15am, on those nightly runs, if there have been
# changes since the last release, it will also auto bump the patch release.
#
# Lastly, it will trigger from manually workflow dispatches.
name: CI and Release
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      rc:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Release Candidate i.e. rc.1 (if applicable)"
        # Input has to be provided for the workflow to run
        required: false
        type: string
      prerelease:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Is this a prerelease?"
        # Input has to be provided for the workflow to run
        required: false
        type: boolean

jobs:
  # yamllint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/yamllint

  # Make a release if
  # - there were changes and this is a scheduled job
  # - This is a manually trigger job, i.e. workflow_dispatch
  release:
    # needs: yamllint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v3
      - name: Version Release
        uses: ./.github/actions/version-release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          version-bump: ${{inputs.version}}
          append-tag: ${{ inputs.rc }}
          prerelease: "${{ inputs.prerelease }}"
