# This workflow is an example of a combination of automatic and manual release.
# The triggers are:
#   - Push
#   - Schedule
#   - Workflow Dispatch
#
# This workflow uses the `if` conditions to control when the CI runs versus when
# a release is also created.
#
# The CI runs when pull requests are created and also when code is merged into
# main, i.e. push events to main.
#
# It will run nightly at 1:15am, on those nightly runs, if there have been
# changes since the last release, it will also auto bump the patch release.
#
# Lastly, it will trigger from manually workflow dispatches.
name: CI and Release
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yamllint

  # Make a prerelease if
  # - there were changes and this is a scheduled job
  # - This is a manually trigger job, i.e. workflow_dispatch
  prerelease:
    needs: yamllint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.version == 'prerelease' }} # yamllint disable-line rule:line-length
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v3
      - name: Prerelease
        uses: ./.github/actions/version-release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          prelease: ${{inputs.version}}

  # Make a release if
  # - there were changes and this is a scheduled job
  # - This is a manually trigger job, i.e. workflow_dispatch
  release:
    needs: yamllint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.version != 'prerelease' }} # yamllint disable-line rule:line-length
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v3
      - name: Version Release
        uses: ./.github/actions/version-release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          version-bump: ${{inputs.version}}
