name: Cron Jobs

on:
  schedule:
    - cron: '* * * * *'

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Anyone there?
        run: |
          echo "Hello World"
