name: Daily
on:
  push:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  stale-PRs:
    uses: ./.github/workflows/reusable_stale.yml
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
