name: Housekeeping

on:
  # triage new issues
  issues:
    types: [opened, edited]
  pull_request:

jobs:
  # calls housekeeping for issues
  housekeeping1:
    # if: contains(github.event.issue.title, 'EPIC')
    uses: ./.github/workflows/reusable_housekeeping.yml
    secrets: inherit
    # strategy:
    #   matrix:
    #     project-url:
    #       - "https://github.com/users/MSevey/projects/1"
    #       - "https://github.com/users/MSevey/projects/2"
    with:
      # Labels
      # run-labels: true
      # labels-to-add: "needs: triage"
      # ignore-if-labeled: true
      # Projects
      run-projects: true
      project-url: "https://github.com/orgs/celestiaorg/projects/22"

  # # calls housekeeping for PRs
  # housekeeping2:
  #   if: ${{ github.event_name == 'pull_request' }}
  #   uses: ./.github/workflows/reusable_housekeeping.yml
  #   secrets: inherit
  #   with:
  #     # Projects
  #     run-projects: true
  #     project-url: "https://github.com/users/MSevey/projects/1"
  #     project-labels: "project"
  #     # Reviewers
  #     run-auto-request-review: true
  #     # reviewer-config-file: "./github/reviewers.yml"
