name: Housekeeping

on:
  # triage new issues
  issues:
    types: [opened]
  pull_request:

jobs:
  housekeeping:
    uses: ./.github/workflows/reusable_housekeeping.yml
    secrets: inherit
    with:
      run-labels: ${{ github.event_name == 'issues' }}
      labels-to-remove: "bug" # not working??
      # run-projects: ${{ github.event_name == 'issues' }}
      # run-auto-request-review: ${{ github.event_name == 'pull_request' }}
