name: Housekeeping

on:
  # triage new issues
  issues:
    types: [opened]
  pull_request:

jobs:
  housekeeping:
    uses: ./.github/workflows/reusable_housekeeping.yml
    secrets: inherit
    with:
      run-labels: ${{ github.event_name == 'issues' }}
      labels-to-add: "needs: triage"
      # labels-to-remove: "test"
      ignore-if-labeled: true
      # run-projects: ${{ github.event_name == 'issues' }}
      run-pr-checklist: ${{ github.event_name == 'pull_request' }}
      # run-auto-request-review: ${{ github.event_name == 'pull_request' }}
