name: Testing Inputs

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      ref:
        description: test
        required: true
        type: string

jobs:
  input_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.ref }}
      - run: echo ${{ github.ref }}
