name: Release Trigger Issue

on:
  release:
    types: [published, released]

jobs:
  baseline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event_name}}"
  published:
    if: ${{ github.event_name == 'published' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "published"
  released:
    if: ${{ github.event_name == 'released' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "released"
  # trigger_issue:
  #   uses: ./.github/workflows/create_issue_epic.yml
  #   secrets: inherit
  #   with:
  #     release-repo: ${{ github.repository }}
  #     release-version: ${{ github.event.release.tag_name }}
