name: Release Trigger Issue

on:
  release:
    types: [published]

jobs:
  trigger_issue:
    uses: ./.github/workflows/create_issue_epic.yml
    secrets: inherit
    with:
      release-repo: ${{ github.repository }}
      release-version: ${{ github.event.release.tag_name }}
