name: Repository Dispatch
on:
  # push:
  workflow_dispatch:
    inputs:
      myEvent:
        description: "Dispatch Event Type"
        required: true
        type: choice
        options:
          - trigger

jobs:
  triggerMyEvent:
    # these evn values can turn into inputs for a reuseable workflow
    env:
      owner: MSevey
      repo: workflows-2
      ref: main
      workflow: repository_dispatch.yml
      workflow_inputs: '{ "key": "my value" }'
      workflow_timeout_seconds: 120
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.PAT_REPO_DISPATCH }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: main # or refs/heads/target_branch
          repo: ${{env.repo}}
          owner: ${{env.owner}}
          workflow: ${{env.workflow}}
          workflow_inputs: ${{ env.workflow_inputs }} # Optional
          workflow_timeout_seconds: ${{env.workflow_timeout_seconds}} # Default: 300

      - name: Use the output run ID
        run: echo '${{toJSON(steps.return_dispatch.outputs)}}'

      - name: Get Conclusion
        uses: octokit/request-action@v2.x
        id: get_run_conclusion
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/{run_id}
          owner: ${{env.owner}}
          repo: ${{env.repo}}
          run_id: ${{steps.return_dispatch.outputs.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delay for api to update
        run: sleep 2

      - name: Check conclusion
        run: "echo latest tag: '${{ fromJSON(steps.get_run_conclusion.outputs.data).conclusion }}'"

      - name: Fail if not successful
        if: ${{ fromJSON(steps.get_run_conclusion.outputs.data).conclusion != 'success' }}
        run: exit 1
        # Alternative if descriptive exit code is helpful
        # uses: actions/github-script@v3
        # with:
        #   script: |
        #       core.setFailed('Coverage test below tolerance')
