name: Repository Dispatch
# run-name: Event Trigger ${{  }}
on:
  push:
  workflow_dispatch:
    inputs:
      myEvent:
        description: "Dispatch Event Type"
        required: true
        type: choice
        options:
          - my-event
          - fail
          - pass-other

jobs:
  triggerMyEvent:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.PAT_REPO_DISPATCH }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: main # or refs/heads/target_branch
          repo: workflows-2
          owner: MSevey
          workflow: repository_dispatch.yml
          # workflow_inputs: '{ "distinct_id": "${{inputs.myEvent}}" }' # Optional
          workflow_timeout_seconds: 120 # Default: 300

      - name: Use the output run ID
        run: echo '${{toJSON(steps.return_dispatch.outputs)}}'

      - name: Get Conclusion
        uses: octokit/request-action@v2.x
        id: get_run_conclusion
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/{run_id}
          owner: MSevey
          repo: workflows-2
          run_id: ${{(steps.return_dispatch.outputs.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check conclusion
        run: "echo latest tag: '${{ fromJSON(steps.get_run_conclusion.outputs.data).conclusion }}'"
