name: Semantic Release

on:
  push:
    branches:
      - main

# unsure about permissions needed

jobs:
  release:
    name: conventional-commit-pr-title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
