# TODO:
# - Ready to test, need to update sync.yml file to target any actual file to sync
# - Test syncing with jinja template for dependabot for the packages
name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.SYNC }}
          PR_LABELS: "action sync"
          COMMIT_PREFIX: "chore:"
          PR_BODY: "Auto PR: syncing from .github repo"
          COMMIT_EACH_FILE: false
